### PR TITLE
refactor(server)!: Reduce code duplication

### PR DESCRIPTION
**Pull request by Manason**
## Description

- replaced qb callbacks with ox_lib callbacks
- update config to use dot notation
- fxmanfiest update from qb to qbx
- extracted common server code of jobs and gangs to main.lua
- breaking change is assuming jobs and gangs will not have the same name

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Review by FjamZoo — APPROVED** [review]
LGTM

**Review by FjamZoo — APPROVED** [review]
LGTM

**Review by FjamZoo — APPROVED** [review]
LGTM

**Review by FjamZoo — APPROVED** [review]
LGTM

**Review by FjamZoo — APPROVED** [review]
LGTM

**Review by FjamZoo — APPROVED** [review]
LGTM

**Comment by trclassic92** [comment]
Nice

**Comment by trclassic92** [comment]
Super Approved

**Pull request merged**
