### PR TITLE
Support for Illenium Boss Management Of Outfits

### PR DESCRIPTION
**Pull request by IgnornceIsBliss**
## Description

Event Trigger for Illenium Outfit Management

## Checklist

- [x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by solareon** [comment]
I believe this just opens the menu to switch outfits. The actual illenium appearance managed outfits is enabled within illenium appearance and adds the menu item dynamically to allow a player to setup outfits for workers.

If you look in shared/config.lua for BossManagedOutfits in illenium appearance that enables the menu

**Comment by IgnornceIsBliss** [comment]
> I believe this just opens the menu to switch outfits. The actual illenium appearance managed outfits is enabled within illenium appearance and adds the menu item dynamically to allow a player to setup outfits for workers.
> 
> If you look in shared/config.lua for BossManagedOutfits in illenium appearance that enables the menu

Correct, However it used to be triggered in qb-management, There is nowhere in illenium to open this management section as it was based on qb-management triggering it which is why i'm adding it back to qbx management

**Comment by solareon** [comment]
> > I believe this just opens the menu to switch outfits. The actual illenium appearance managed outfits is enabled within illenium appearance and adds the menu item dynamically to allow a player to setup outfits for workers.
> 
> > 
> 
> > If you look in shared/config.lua for BossManagedOutfits in illenium appearance that enables the menu
> 
> 
> 
> Correct, However it used to be triggered in qb-management, There is nowhere in illenium to open this management section as it was based on qb-management triggering it which is why i'm adding it back to qbx management

These are designed to be defined under 
Config.ClothingRooms in illenium that way all the workers can access the configured outfits set through the BossManagedOutfits menu. 

Adding the event that just lets you change to any outfit isn't how it was supposed to work. It should let you define managed outfits in the qbx_management menu that can then be selected by any employee in the ClothingRooms section in illenium.

**Comment by IgnornceIsBliss** [comment]
image

This is how it is when i add trigger to qbx management like i expected, Below is how it is from the clothing room config like you suggest, Very different options

image

**Comment by solareon** [comment]
Okay I think we have a bit of confusion. You need to utilize both configuration options in illenium. The first for the extra menu to appear in the boss menu. The second for players to be able to select the defined job outfits which will function as job clothes allowing the player to easily switch back to their non job clothes and then also to theoretically enable you to lock job clothes from regular selections to prevent imposters.

**Comment by IgnornceIsBliss** [comment]
> Okay I think we have a bit of confusion. You need to utilize both configuration options in illenium. The first for the extra menu to appear in the boss menu. The second for players to be able to select the defined job outfits which will function as job clothes allowing the player to easily switch back to their non job clothes and then also to theoretically enable you to lock job clothes from regular selections to prevent imposters.

Note sure what you're referencing

image


I've enabled the boss managed option, The only way to change the outfits with illenium is hard coding it in the config, Which is not the same as what i added to qbx management.

**Comment by solareon** [comment]
When you have that option enabled and save an outfit in that additional menu that appears then go to one of the Config.ClothingRooms does it not show the saved outfit there?

You might need to check if the 'management_outfits' database table exists.

I apologize for my short replies, GitHub mobile isn't great for making line references.

**Comment by IgnornceIsBliss** [comment]
> When you have that option enabled and save an outfit in that additional menu that appears then go to one of the Config.ClothingRooms does it not show the saved outfit there?

The only way to save a job outfit is how i've added it to qbx management which is the whole point of this PR, By going to the Config.ClothingRooms it only shows the existing outfits that are hardcoded, Wheras with what i added you can save the outifts live, There is even QBX Management support built into illenium by default for this very function...

**Comment by mafewtm** [comment]
> > When you have that option enabled and save an outfit in that additional menu that appears then go to one of the Config.ClothingRooms does it not show the saved outfit there?
> 
> The only way to save a job outfit is how i've added it to qbx management which is the whole point of this PR, By going to the Config.ClothingRooms it only shows the existing outfits that are hardcoded, Wheras with what i added you can save the outifts live, There is even QBX Management support built into illenium by default for this very function...

You mean this right [here](https://github.com/iLLeniumStudios/illenium-appearance/blob/main/client/management/qbx.lua)? Which is already added through the preexisting code?

**Comment by mafewtm** [comment]
Stale PR

**Pull request closed without merging**
